version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: cat /dev/null | sbt test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: cat /dev/null | sbt test:test
      - codecov/upload:
          file: target/test-reports/TEST-com.warren_r.sparkutils.snapshot.SnapshotTestTest.xml