version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: sbt test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: sbt clean coverage test
      - run: sbt coverageReport
      - codecov/upload:
          file: /home/circleci/repo/target/scala-2.12/scoverage-report/scoverage.xml